/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import controller.BatchController;
import controller.StudentController;
import controller.UserController;
import model.Batch;
import model.Student;
import model.Users;

/**
 *
 * @author thaond
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    Vector tableBatch_tieuDe = new Vector();
    Vector tableBatch_duLieu = new Vector();
    private BatchController batchController = new BatchController();
    private StudentController studentController = new StudentController();
    private UserController userController = new UserController();
    private List<String> batchIds = new ArrayList<>();

    public frmMain() {
        initComponents();
        panelThongTin.add(panelBatch, "panelBatch");
        panelThongTin.add(panelStudent, "panelStudent");
        panelThongTin.add(panelUsers, "panelUsers");
        btnBatch.doClick();
    }
    
    // CHUA XONG
    
    private Map<String,String> getStudentMap(){
        Map<String,String> results = new HashMap<>();
        return results;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogBatch_new = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDialogBatch_txt_BatchId = new javax.swing.JTextField();
        jDialog_txt_BatchName = new javax.swing.JTextField();
        jDialogBatch_btn_add = new javax.swing.JButton();
        jDialogBatch_labelMessage1 = new javax.swing.JLabel();
        jDialogBatch_labelMessage2 = new javax.swing.JLabel();
        jDialogBatch_Edit = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDialogBatch_txt_editBatchId = new javax.swing.JTextField();
        jDialogbatch_txt_editBatchName = new javax.swing.JTextField();
        jDialogBatch_btnEdit = new javax.swing.JButton();
        jDialogStudent_new = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDialogStudent_new_txt_StudentId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDialogStudent_new_txt_StudentName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton_New_Male = new javax.swing.JRadioButton();
        jRadioButton_New_Female = new javax.swing.JRadioButton();
        jComboBox_New_BatchIds = new javax.swing.JComboBox<>();
        jRadioButton_New_Orther = new javax.swing.JRadioButton();
        jDialogStudent_new_btn_add = new javax.swing.JButton();
        btnGroup_New_studentGender = new javax.swing.ButtonGroup();
        jDialogStudent_Edit = new javax.swing.JDialog();
        jDialogStudent_Edit_btn_add = new javax.swing.JButton();
        jRadioButton_Edit_Female = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton_Edit_Male = new javax.swing.JRadioButton();
        jRadioButton_Edit_Orther = new javax.swing.JRadioButton();
        jDialogStudent_Edit_txt_StudentName = new javax.swing.JTextField();
        jComboBox_Edit_BatchIds = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDialogStudent_Edit_txt_StudentId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        buttonGroup_Edit_studentGender = new javax.swing.ButtonGroup();
        jDialogUser_New = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jDialogUser_New_txt_UserName = new javax.swing.JTextField();
        jComboBox_New_StudentId = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDIalogUser_New_txt_password = new javax.swing.JPasswordField();
        jDialogUser_New_btn_Add = new javax.swing.JButton();
        jDIalogUser_New_txt_password1 = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jDialogUser_Edit = new javax.swing.JDialog();
        jDialogUser_New_btn_Edit = new javax.swing.JButton();
        jDIalogUser_Edit_txt_password = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox_Edit_StudentId = new javax.swing.JComboBox<>();
        jDialogUser_Edit_txt_UserName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jDIalogUser_Edit_txt_password1 = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBatch = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        panelThongTin = new javax.swing.JPanel();
        panelBatch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBatch = new javax.swing.JTable();
        btnNewBatch = new javax.swing.JButton();
        btnEditBatch = new javax.swing.JButton();
        btnDeleteBatch = new javax.swing.JButton();
        panelStudent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStudent = new javax.swing.JTable();
        btnNewStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        panelUsers = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();
        btnNewUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();

        jLabel1.setText("Batch id");

        jLabel2.setText("Batch name");

        jDialogBatch_txt_BatchId.setEditable(false);
        jDialogBatch_txt_BatchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogBatch_txt_BatchIdActionPerformed(evt);
            }
        });

        jDialogBatch_btn_add.setText("Save");
        jDialogBatch_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogBatch_btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogBatch_newLayout = new javax.swing.GroupLayout(jDialogBatch_new.getContentPane());
        jDialogBatch_new.getContentPane().setLayout(jDialogBatch_newLayout);
        jDialogBatch_newLayout.setHorizontalGroup(
            jDialogBatch_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBatch_newLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jDialogBatch_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(64, 64, 64)
                .addGroup(jDialogBatch_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDialogBatch_labelMessage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDialogBatch_txt_BatchId)
                    .addComponent(jDialog_txt_BatchName, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jDialogBatch_labelMessage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogBatch_newLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(jDialogBatch_btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        jDialogBatch_newLayout.setVerticalGroup(
            jDialogBatch_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBatch_newLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDialogBatch_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDialogBatch_txt_BatchId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDialogBatch_labelMessage1)
                .addGap(22, 22, 22)
                .addGroup(jDialogBatch_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDialog_txt_BatchName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDialogBatch_labelMessage2)
                .addGap(18, 18, 18)
                .addComponent(jDialogBatch_btn_add)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jLabel3.setText("Batch id");

        jLabel4.setText("Batch name");

        jDialogbatch_txt_editBatchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogbatch_txt_editBatchNameActionPerformed(evt);
            }
        });

        jDialogBatch_btnEdit.setText("Save");
        jDialogBatch_btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogBatch_btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogBatch_EditLayout = new javax.swing.GroupLayout(jDialogBatch_Edit.getContentPane());
        jDialogBatch_Edit.getContentPane().setLayout(jDialogBatch_EditLayout);
        jDialogBatch_EditLayout.setHorizontalGroup(
            jDialogBatch_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBatch_EditLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jDialogBatch_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogBatch_EditLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jDialogBatch_txt_editBatchId, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogBatch_EditLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jDialogBatch_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDialogBatch_btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDialogbatch_txt_editBatchName))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jDialogBatch_EditLayout.setVerticalGroup(
            jDialogBatch_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBatch_EditLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jDialogBatch_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDialogBatch_txt_editBatchId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jDialogBatch_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDialogbatch_txt_editBatchName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jDialogBatch_btnEdit)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel5.setText("Batch id");

        jLabel6.setText("Student id");

        jDialogStudent_new_txt_StudentId.setEditable(false);
        jDialogStudent_new_txt_StudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogStudent_new_txt_StudentIdActionPerformed(evt);
            }
        });

        jLabel7.setText("Student name");

        jDialogStudent_new_txt_StudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogStudent_new_txt_StudentNameActionPerformed(evt);
            }
        });

        jLabel8.setText("gender");

        btnGroup_New_studentGender.add(jRadioButton_New_Male);
        jRadioButton_New_Male.setText("Male");
        jRadioButton_New_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_New_MaleActionPerformed(evt);
            }
        });

        btnGroup_New_studentGender.add(jRadioButton_New_Female);
        jRadioButton_New_Female.setText("Female");
        jRadioButton_New_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_New_FemaleActionPerformed(evt);
            }
        });

        jComboBox_New_BatchIds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGroup_New_studentGender.add(jRadioButton_New_Orther);
        jRadioButton_New_Orther.setText("orther");
        jRadioButton_New_Orther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_New_OrtherActionPerformed(evt);
            }
        });

        jDialogStudent_new_btn_add.setText("Save");
        jDialogStudent_new_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogStudent_new_btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogStudent_newLayout = new javax.swing.GroupLayout(jDialogStudent_new.getContentPane());
        jDialogStudent_new.getContentPane().setLayout(jDialogStudent_newLayout);
        jDialogStudent_newLayout.setHorizontalGroup(
            jDialogStudent_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogStudent_newLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jDialogStudent_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogStudent_newLayout.createSequentialGroup()
                        .addGroup(jDialogStudent_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialogStudent_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDialogStudent_new_txt_StudentId, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jComboBox_New_BatchIds, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDialogStudent_newLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButton_New_Male)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_New_Female)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_New_Orther)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(jDialogStudent_newLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDialogStudent_new_txt_StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
            .addGroup(jDialogStudent_newLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jDialogStudent_new_btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogStudent_newLayout.setVerticalGroup(
            jDialogStudent_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogStudent_newLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jDialogStudent_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_New_BatchIds, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogStudent_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDialogStudent_new_txt_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogStudent_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDialogStudent_new_txt_StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jDialogStudent_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton_New_Male)
                    .addComponent(jRadioButton_New_Female)
                    .addComponent(jRadioButton_New_Orther))
                .addGap(18, 18, 18)
                .addComponent(jDialogStudent_new_btn_add)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jDialogStudent_Edit_btn_add.setText("Save");
        jDialogStudent_Edit_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogStudent_Edit_btn_addActionPerformed(evt);
            }
        });

        buttonGroup_Edit_studentGender.add(jRadioButton_Edit_Female);
        jRadioButton_Edit_Female.setText("Female");
        jRadioButton_Edit_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Edit_FemaleActionPerformed(evt);
            }
        });

        jLabel9.setText("gender");

        buttonGroup_Edit_studentGender.add(jRadioButton_Edit_Male);
        jRadioButton_Edit_Male.setText("Male");
        jRadioButton_Edit_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Edit_MaleActionPerformed(evt);
            }
        });

        buttonGroup_Edit_studentGender.add(jRadioButton_Edit_Orther);
        jRadioButton_Edit_Orther.setText("orther");
        jRadioButton_Edit_Orther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Edit_OrtherActionPerformed(evt);
            }
        });

        jDialogStudent_Edit_txt_StudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogStudent_Edit_txt_StudentNameActionPerformed(evt);
            }
        });

        jComboBox_Edit_BatchIds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Student name");

        jLabel11.setText("Student id");

        jDialogStudent_Edit_txt_StudentId.setEditable(false);
        jDialogStudent_Edit_txt_StudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogStudent_Edit_txt_StudentIdActionPerformed(evt);
            }
        });

        jLabel12.setText("Batch id");

        javax.swing.GroupLayout jDialogStudent_EditLayout = new javax.swing.GroupLayout(jDialogStudent_Edit.getContentPane());
        jDialogStudent_Edit.getContentPane().setLayout(jDialogStudent_EditLayout);
        jDialogStudent_EditLayout.setHorizontalGroup(
            jDialogStudent_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogStudent_EditLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jDialogStudent_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogStudent_EditLayout.createSequentialGroup()
                        .addGroup(jDialogStudent_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialogStudent_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDialogStudent_Edit_txt_StudentId, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jComboBox_Edit_BatchIds, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDialogStudent_EditLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButton_Edit_Male)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_Edit_Female)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_Edit_Orther)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(jDialogStudent_EditLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDialogStudent_Edit_txt_StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
            .addGroup(jDialogStudent_EditLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jDialogStudent_Edit_btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogStudent_EditLayout.setVerticalGroup(
            jDialogStudent_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogStudent_EditLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jDialogStudent_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Edit_BatchIds, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogStudent_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDialogStudent_Edit_txt_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogStudent_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDialogStudent_Edit_txt_StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jDialogStudent_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButton_Edit_Male)
                    .addComponent(jRadioButton_Edit_Female)
                    .addComponent(jRadioButton_Edit_Orther))
                .addGap(18, 18, 18)
                .addComponent(jDialogStudent_Edit_btn_add)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel13.setText("Student Id");

        jComboBox_New_StudentId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("User name");

        jLabel15.setText("Re- Password");

        jDialogUser_New_btn_Add.setText("Save");
        jDialogUser_New_btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogUser_New_btn_AddActionPerformed(evt);
            }
        });

        jLabel19.setText("Password");

        javax.swing.GroupLayout jDialogUser_NewLayout = new javax.swing.GroupLayout(jDialogUser_New.getContentPane());
        jDialogUser_New.getContentPane().setLayout(jDialogUser_NewLayout);
        jDialogUser_NewLayout.setHorizontalGroup(
            jDialogUser_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogUser_NewLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jDialogUser_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jDialogUser_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDialogUser_New_btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDialogUser_New_txt_UserName)
                    .addComponent(jComboBox_New_StudentId, 0, 206, Short.MAX_VALUE)
                    .addComponent(jDIalogUser_New_txt_password)
                    .addComponent(jDIalogUser_New_txt_password1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60))
        );
        jDialogUser_NewLayout.setVerticalGroup(
            jDialogUser_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogUser_NewLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDialogUser_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_New_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jDialogUser_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDialogUser_New_txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogUser_NewLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jDialogUser_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogUser_NewLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDIalogUser_New_txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDialogUser_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDIalogUser_New_txt_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialogUser_NewLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jDialogUser_New_btn_Add)
                .addGap(33, 33, 33))
        );

        jDialogUser_New_btn_Edit.setText("Save");
        jDialogUser_New_btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDialogUser_New_btn_EditActionPerformed(evt);
            }
        });

        jLabel16.setText("Re-Password");

        jLabel17.setText("User name");

        jComboBox_Edit_StudentId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jDialogUser_Edit_txt_UserName.setEditable(false);

        jLabel18.setText("Student Id");

        jLabel20.setText("Password");

        javax.swing.GroupLayout jDialogUser_EditLayout = new javax.swing.GroupLayout(jDialogUser_Edit.getContentPane());
        jDialogUser_Edit.getContentPane().setLayout(jDialogUser_EditLayout);
        jDialogUser_EditLayout.setHorizontalGroup(
            jDialogUser_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogUser_EditLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jDialogUser_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jDialogUser_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDialogUser_New_btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDialogUser_Edit_txt_UserName)
                    .addComponent(jComboBox_Edit_StudentId, 0, 206, Short.MAX_VALUE)
                    .addComponent(jDIalogUser_Edit_txt_password)
                    .addComponent(jDIalogUser_Edit_txt_password1))
                .addGap(60, 60, 60))
        );
        jDialogUser_EditLayout.setVerticalGroup(
            jDialogUser_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogUser_EditLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDialogUser_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Edit_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jDialogUser_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDialogUser_Edit_txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogUser_EditLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogUser_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDIalogUser_Edit_txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogUser_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDIalogUser_Edit_txt_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jDialogUser_New_btn_Edit)
                .addGap(46, 46, 46))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBatch.setText("Batch");
        btnBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatchActionPerformed(evt);
            }
        });

        btnStudent.setText("Student");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnUsers.setText("Users");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatch)
                    .addComponent(btnStudent)
                    .addComponent(btnUsers))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatch, btnStudent, btnUsers});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsers)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        panelThongTin.setLayout(new java.awt.CardLayout());

        tableBatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBatch.setShowHorizontalLines(false);
        tableBatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableBatchMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableBatch);

        btnNewBatch.setText("New batch");
        btnNewBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBatchActionPerformed(evt);
            }
        });

        btnEditBatch.setText("Edit batch");
        btnEditBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBatchActionPerformed(evt);
            }
        });

        btnDeleteBatch.setText("Delete batch");
        btnDeleteBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBatchLayout = new javax.swing.GroupLayout(panelBatch);
        panelBatch.setLayout(panelBatchLayout);
        panelBatchLayout.setHorizontalGroup(
            panelBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBatchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(panelBatchLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnNewBatch)
                .addGap(18, 18, 18)
                .addComponent(btnEditBatch)
                .addGap(26, 26, 26)
                .addComponent(btnDeleteBatch)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        panelBatchLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteBatch, btnEditBatch, btnNewBatch});

        panelBatchLayout.setVerticalGroup(
            panelBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBatchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewBatch)
                    .addComponent(btnEditBatch)
                    .addComponent(btnDeleteBatch))
                .addContainerGap())
        );

        panelThongTin.add(panelBatch, "card2");

        tableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableStudent);

        btnNewStudent.setText("New student");
        btnNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewStudentActionPerformed(evt);
            }
        });

        btnEditStudent.setText("Edit student");
        btnEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStudentActionPerformed(evt);
            }
        });

        btnDeleteStudent.setText("Delete student");
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnNewStudent)
                .addGap(18, 18, 18)
                .addComponent(btnEditStudent)
                .addGap(26, 26, 26)
                .addComponent(btnDeleteStudent)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewStudent)
                    .addComponent(btnEditStudent)
                    .addComponent(btnDeleteStudent))
                .addContainerGap())
        );

        panelThongTin.add(panelStudent, "card3");

        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableUsers);

        btnNewUser.setText("New user");
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });

        btnEditUser.setText("Edit user");
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Delete user");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsersLayout = new javax.swing.GroupLayout(panelUsers);
        panelUsers.setLayout(panelUsersLayout);
        panelUsersLayout.setHorizontalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnNewUser)
                .addGap(18, 18, 18)
                .addComponent(btnEditUser)
                .addGap(26, 26, 26)
                .addComponent(btnDeleteUser)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        panelUsersLayout.setVerticalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewUser)
                    .addComponent(btnEditUser)
                    .addComponent(btnDeleteUser))
                .addContainerGap())
        );

        panelThongTin.add(panelUsers, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatchActionPerformed
        List<Batch> listBatch = batchController.getAll();
        tableBatch_tieuDe.clear();
        tableBatch_tieuDe.add("STT");
        tableBatch_tieuDe.add("Batch ID");
        tableBatch_tieuDe.add("Batch name");
        tableBatch_duLieu.clear();
        for (int i = 0; i < listBatch.size(); i++) {
            Vector temp = new Vector();
            temp.add(i + 1);
            temp.add(listBatch.get(i).getId());
            temp.add(listBatch.get(i).getBatchName());
            tableBatch_duLieu.add(temp);
        }
        DefaultTableModel model = new DefaultTableModel(tableBatch_duLieu, tableBatch_tieuDe) {
            @Override
            public boolean isCellEditable(int i, int i1) {
//                    if ((i1 == 0) || (i1 == 2)) {
//                        return true;
//                    } else {
//                        return false;
//                    }
                return false;
            }

        };
        tableBatch.setModel(model);
        CardLayout layout = (CardLayout) panelThongTin.getLayout();
        layout.show(panelThongTin, "panelBatch");
    }//GEN-LAST:event_btnBatchActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        List<Student> listStudent = studentController.getAll();
        tableBatch_tieuDe.clear();
        tableBatch_tieuDe.add("STT");
        tableBatch_tieuDe.add("Student id");
        tableBatch_tieuDe.add("Student name");
        tableBatch_tieuDe.add("Student gender");
        tableBatch_tieuDe.add("batch");
        tableBatch_duLieu.clear();
        for (int i = 0; i < listStudent.size(); i++) {
            Vector temp = new Vector();
            temp.add(i + 1);
            temp.add(listStudent.get(i).getId());
            temp.add(listStudent.get(i).getStudentname());
            temp.add(listStudent.get(i).getStudentgender());
            temp.add(listStudent.get(i).getBatchid());
            tableBatch_duLieu.add(temp);
        }
        DefaultTableModel model = new DefaultTableModel(tableBatch_duLieu, tableBatch_tieuDe) {
            @Override
            public boolean isCellEditable(int i, int i1) {
//                    if ((i1 == 0) || (i1 == 2)) {
//                        return true;
//                    } else {
//                        return false;
//                    }
                return false;
            }
        };
        tableStudent.setModel(model);
        CardLayout layout = (CardLayout) panelThongTin.getLayout();
        layout.show(panelThongTin, "panelStudent");
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        List<Users> listUsers = userController.getAll();
        tableBatch_tieuDe.clear();
        tableBatch_tieuDe.add("STT");
        tableBatch_tieuDe.add("User name");
        tableBatch_tieuDe.add("password");
        tableBatch_tieuDe.add("Student name");
        tableBatch_duLieu.clear();
        for (int i = 0; i < listUsers.size(); i++) {
            Vector temp = new Vector();
            temp.add(i + 1);
            temp.add(listUsers.get(i).getUsername());
            temp.add(listUsers.get(i).getPassword());
            temp.add(listUsers.get(i).getStudentid());
            tableBatch_duLieu.add(temp);
        }
        DefaultTableModel model = new DefaultTableModel(tableBatch_duLieu, tableBatch_tieuDe) {
            @Override
            public boolean isCellEditable(int i, int i1) {
//                    if ((i1 == 0) || (i1 == 2)) {
//                        return true;
//                    } else {
//                        return false;
//                    }
                return false;
            }
        };
        tableUsers.setModel(model);
        CardLayout layout = (CardLayout) panelThongTin.getLayout();
        layout.show(panelThongTin, "panelUsers");
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnDeleteBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBatchActionPerformed
        int[] countBatchs = tableBatch.getSelectedRows();
        int count = 0;
        String batch = "";
        if (countBatchs.length == 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn Batch cần xóa", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean flag = false;
            for (int i = 0; i < countBatchs.length; i++) {
                if (studentController.findByBatchId(tableBatch.getValueAt(countBatchs[i], 1).toString())) {
                    batch = tableBatch.getValueAt(countBatchs[i], 1).toString();
                    flag = false;
                    break;
                } else {
                    batchController.delBatch(tableBatch.getValueAt(countBatchs[i], 1).toString());
                    count++;
                    flag = true;
                }
            }
            if (flag == true) {
                JOptionPane.showMessageDialog(null, "Xóa thành công", "THÔNG BÁO", HEIGHT);
            } else {
                JOptionPane.showMessageDialog(null, "Đã xóa " + count + " batch \n Batch " + batch
                        + " đang tồn tại trong danh sách sinh viên. Phải xóa từ danh sách sinh viên", "THÔNG BÁO", HEIGHT);
            }
        }
        btnBatch.doClick();
    }//GEN-LAST:event_btnDeleteBatchActionPerformed

    private void tableBatchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBatchMouseReleased

    }//GEN-LAST:event_tableBatchMouseReleased

    private void btnNewBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBatchActionPerformed
        String temp = batchController.getLastBatchId();
        if (temp.isEmpty()) {
            jDialogBatch_txt_BatchId.setText("batch00001");
        } else {
            Pattern pattern = Pattern.compile("\\d+");
            Matcher m = pattern.matcher(temp);
            int flag = 0;
            String prefixBatch = "";
            if (m.find()) {
                flag = Integer.valueOf(m.group());
            }
            if (String.valueOf(flag + 1).length() > String.valueOf(flag).length()) {
                prefixBatch = temp.substring(0, (temp.indexOf(String.valueOf(flag)) - 1));
            } else {
                prefixBatch = temp.substring(0, temp.indexOf(String.valueOf(flag)));
            }
            jDialogBatch_txt_BatchId.setText(prefixBatch + (flag + 1));
        }
        jDialogBatch_new.pack();
        jDialogBatch_new.setLocationRelativeTo(this);
        jDialogBatch_new.setVisible(true);
    }//GEN-LAST:event_btnNewBatchActionPerformed

    private void jDialogBatch_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogBatch_btn_addActionPerformed
        if (jDialog_txt_BatchName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập batch name", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            jDialog_txt_BatchName.requestFocus();
        } else if (jDialog_txt_BatchName.getText().trim().length() > 50) {
            JOptionPane.showMessageDialog(this, "batch name không được quá 50 kí tự", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDialog_txt_BatchName.requestFocus();
            jDialog_txt_BatchName.selectAll();
        } else {
            Batch batch = new Batch(jDialogBatch_txt_BatchId.getText(), jDialog_txt_BatchName.getText());
            int result = batchController.addBatch(batch);
            if (result != 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            }
            btnBatch.doClick();
            jDialog_txt_BatchName.setText("");
            jDialog_txt_BatchName.requestFocus();
            btnNewBatch.doClick();
        }
    }//GEN-LAST:event_jDialogBatch_btn_addActionPerformed

    private void jDialogBatch_txt_BatchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogBatch_txt_BatchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogBatch_txt_BatchIdActionPerformed

    private void btnEditBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBatchActionPerformed
        int count = tableBatch.getSelectedRow();
        if (count == -1) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập batch muốn sửa", "THÔNG BÁO", HEIGHT);
        } else {
            String batchid = tableBatch.getValueAt(count, 1).toString();
            jDialogBatch_txt_editBatchId.setEditable(false);
            jDialogBatch_txt_editBatchId.setText(batchid);
            jDialogbatch_txt_editBatchName.setText(tableBatch.getValueAt(count, 2).toString());
            jDialogbatch_txt_editBatchName.requestFocus();
            jDialogbatch_txt_editBatchName.selectAll();
            jDialogBatch_Edit.pack();
            jDialogBatch_Edit.setLocationRelativeTo(this);
            jDialogBatch_Edit.setVisible(true);
        }
    }//GEN-LAST:event_btnEditBatchActionPerformed

    private void jDialogbatch_txt_editBatchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogbatch_txt_editBatchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogbatch_txt_editBatchNameActionPerformed

    private void jDialogBatch_btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogBatch_btnEditActionPerformed
        if (jDialogbatch_txt_editBatchName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập batch name", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            jDialogbatch_txt_editBatchName.requestFocus();
        } else if (jDialogbatch_txt_editBatchName.getText().trim().length() > 50) {
            JOptionPane.showMessageDialog(this, "batch name không được vượt quá 50 kí tự", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDialogbatch_txt_editBatchName.requestFocus();
            jDialogbatch_txt_editBatchName.selectAll();
        } else {
            Batch batch = new Batch(jDialogBatch_txt_editBatchId.getText(), jDialogbatch_txt_editBatchName.getText());
            int result = batchController.editBatch(batch);
            if (result != 0) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            }
        }
        btnBatch.doClick();
        jDialogBatch_Edit.dispose();
    }//GEN-LAST:event_jDialogBatch_btnEditActionPerformed

    private void jDialogStudent_new_txt_StudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogStudent_new_txt_StudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogStudent_new_txt_StudentNameActionPerformed

    private void jDialogStudent_new_txt_StudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogStudent_new_txt_StudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogStudent_new_txt_StudentIdActionPerformed

    private void btnNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewStudentActionPerformed
        String temp = studentController.getLastStudentId();
        if (temp.isEmpty()) {
            jDialogStudent_new_txt_StudentId.setText("student001");
        } else {
            Pattern pattern = Pattern.compile("\\d+");
            Matcher m = pattern.matcher(temp);
            int flag = 0;
            String prefixBatch = "";
            if (m.find()) {
                flag = Integer.valueOf(m.group());
            }
            if (String.valueOf(flag + 1).length() > String.valueOf(flag).length()) {
                prefixBatch = temp.substring(0, (temp.indexOf(String.valueOf(flag)) - 1));
            } else {
                prefixBatch = temp.substring(0, temp.indexOf(String.valueOf(flag)));
            }
            jDialogStudent_new_txt_StudentId.setText(prefixBatch + (flag + 1));
        }
        List<Batch> listBatch = batchController.getAll();
        batchIds = listBatch.stream().map(item -> item.getId()).collect(Collectors.toList());
        jComboBox_New_BatchIds.removeAllItems();
        batchIds.forEach((string) -> {
            jComboBox_New_BatchIds.addItem(string);
        });
        if (jComboBox_New_BatchIds.getSelectedItem() != null) {
            jRadioButton_New_Male.setSelected(true);
            jRadioButton_New_Male.doClick();
            jDialogStudent_new.pack();
            jDialogStudent_new.setLocationRelativeTo(this);
            jDialogStudent_new.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Phải thêm batch trước khi thêm sinh viên", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNewStudentActionPerformed

    private void jDialogStudent_new_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogStudent_new_btn_addActionPerformed
        if (jDialogStudent_new_txt_StudentName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên sinh viên", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            jDialogStudent_new_txt_StudentName.requestFocus();
        } else if (jDialogStudent_new_txt_StudentName.getText().trim().length() > 50) {
            JOptionPane.showMessageDialog(this, "Tên sinh viên không được vượt quá 50 kí tự", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDialogStudent_new_txt_StudentName.requestFocus();
            jDialogStudent_new_txt_StudentName.selectAll();
        } else {
            String studentId = jDialogStudent_new_txt_StudentId.getText();
            String studentName = jDialogStudent_new_txt_StudentName.getText();
            String studentGender = btnGroup_New_studentGender.getSelection().getActionCommand();
            String batchId = jComboBox_New_BatchIds.getSelectedItem().toString();
            Student student = new Student(studentId, studentName, studentGender, batchId);
            int result = studentController.addStudent(student);
            if (result != 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            }
            btnStudent.doClick();
            jDialogStudent_new_txt_StudentName.setText("");
            jDialogStudent_new_txt_StudentName.requestFocus();
            btnNewStudent.doClick();
        }
    }//GEN-LAST:event_jDialogStudent_new_btn_addActionPerformed

    private void jRadioButton_New_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_New_MaleActionPerformed
        jRadioButton_New_Male.setActionCommand("nam");
    }//GEN-LAST:event_jRadioButton_New_MaleActionPerformed

    private void jRadioButton_New_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_New_FemaleActionPerformed
        jRadioButton_New_Female.setActionCommand("nu");
    }//GEN-LAST:event_jRadioButton_New_FemaleActionPerformed

    private void jRadioButton_New_OrtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_New_OrtherActionPerformed
        jRadioButton_New_Orther.setActionCommand("khac");
    }//GEN-LAST:event_jRadioButton_New_OrtherActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed
        int count = tableStudent.getSelectedRow();
        if (count == -1) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn sinh viên muốn sửa", "THÔNG BÁO", HEIGHT);
        } else {
            List<Batch> listBatch = batchController.getAll();
            batchIds = listBatch.stream().map(item -> item.getId()).collect(Collectors.toList());
            jComboBox_Edit_BatchIds.removeAllItems();
            batchIds.forEach((string) -> {
                jComboBox_Edit_BatchIds.addItem(string);
            });
            jComboBox_Edit_BatchIds.setSelectedItem(tableStudent.getValueAt(count, 4).toString());
            jDialogStudent_Edit_txt_StudentId.setText(tableStudent.getValueAt(count, 1).toString());
            jDialogStudent_Edit_txt_StudentName.setText(tableStudent.getValueAt(count, 2).toString());
            jDialogStudent_Edit_txt_StudentName.requestFocus();
            jDialogStudent_Edit_txt_StudentName.selectAll();
            String gender = tableStudent.getValueAt(tableStudent.getSelectedRow(), 3).toString();
            if (gender.equalsIgnoreCase("nam")) {
                jRadioButton_Edit_Male.setSelected(true);
                jRadioButton_Edit_Male.doClick();
            } else if (gender.equalsIgnoreCase("nu")) {
                jRadioButton_Edit_Female.setSelected(true);
                jRadioButton_Edit_Male.doClick();
            } else {
                jRadioButton_Edit_Orther.setSelected(true);
                jRadioButton_Edit_Orther.doClick();
            }
            jDialogStudent_Edit.pack();
            jDialogStudent_Edit.setLocationRelativeTo(this);
            jDialogStudent_Edit.setVisible(true);
        }

    }//GEN-LAST:event_btnEditStudentActionPerformed

    private void jDialogStudent_Edit_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogStudent_Edit_btn_addActionPerformed
        if (jDialogStudent_Edit_txt_StudentName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên sinh viên", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            jDialogStudent_Edit_txt_StudentName.requestFocus();
        } else if (jDialogStudent_Edit_txt_StudentName.getText().trim().length() > 50) {
            JOptionPane.showMessageDialog(this, "Tên sinh viên không được vượt quá 50 kí tự", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDialogStudent_Edit_txt_StudentName.requestFocus();
            jDialogStudent_Edit_txt_StudentName.selectAll();
        } else {
            String studentId = jDialogStudent_Edit_txt_StudentId.getText();
            String studentName = jDialogStudent_Edit_txt_StudentName.getText();
            String studentGender = buttonGroup_Edit_studentGender.getSelection().getActionCommand();
            System.out.println(studentGender);
            String batchId = jComboBox_Edit_BatchIds.getSelectedItem().toString();
            Student student = new Student(studentId, studentName, studentGender, batchId);
            int result = studentController.editStudent(student);
            if (result != 0) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            }
        }
        btnStudent.doClick();
        jDialogStudent_Edit.dispose();
    }//GEN-LAST:event_jDialogStudent_Edit_btn_addActionPerformed

    private void jRadioButton_Edit_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Edit_FemaleActionPerformed
        jRadioButton_Edit_Female.setActionCommand("nu");
    }//GEN-LAST:event_jRadioButton_Edit_FemaleActionPerformed

    private void jRadioButton_Edit_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Edit_MaleActionPerformed
        jRadioButton_Edit_Male.setActionCommand("nam");
    }//GEN-LAST:event_jRadioButton_Edit_MaleActionPerformed

    private void jRadioButton_Edit_OrtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Edit_OrtherActionPerformed
        jRadioButton_Edit_Orther.setActionCommand("khac");
    }//GEN-LAST:event_jRadioButton_Edit_OrtherActionPerformed

    private void jDialogStudent_Edit_txt_StudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogStudent_Edit_txt_StudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogStudent_Edit_txt_StudentNameActionPerformed

    private void jDialogStudent_Edit_txt_StudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogStudent_Edit_txt_StudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogStudent_Edit_txt_StudentIdActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        int[] countStudents = tableStudent.getSelectedRows();
        int count = 0;
        String studentId = "";
        if (countStudents.length == 0) {
            JOptionPane.showMessageDialog(null, "Chọn sinh viên cần xóa", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean flag = false;
            for (int i = 0; i < countStudents.length; i++) {
                if (userController.findByStudentId(tableStudent.getValueAt(countStudents[i], 1).toString())) {
                    studentId = tableStudent.getValueAt(countStudents[i], 1).toString();
                    flag = false;
                    break;
                } else {
                    studentController.delStudent(tableStudent.getValueAt(countStudents[i], 1).toString());
                    count++;
                    flag = true;
                }
            }
            if (flag == true) {
                JOptionPane.showMessageDialog(null, "Xóa thành công", "THÔNG BÁO", HEIGHT);
            } else {
                JOptionPane.showMessageDialog(null, "Đã xóa" + count + " sinh viên \n sinh viên " + studentId
                        + " đang tồn tại trong danh sách người dùng. Phải xóa từ danh sách người dùng trước ", "THÔNG BÁO", HEIGHT);
            }
        }
        btnStudent.doClick();
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        /*long temp = userController.getLastUserId();
        if (temp == -1) {
            jDialogStudent_new_txt_StudentId.setText("student001");
        } else {
            Pattern pattern = Pattern.compile("\\d+");
            Matcher m = pattern.matcher(temp);
            int flag = 0;
            String prefixBatch = "";
            if (m.find()) {
                flag = Integer.valueOf(m.group());
            }
            if (String.valueOf(flag + 1).length() > String.valueOf(flag).length()) {
                prefixBatch = temp.substring(0, (temp.indexOf(String.valueOf(flag)) - 1));
            } else {
                prefixBatch = temp.substring(0, temp.indexOf(String.valueOf(flag)));
            }
            jDialogU_new_txt_StudentId.setText(prefixBatch + (flag + 1));
        }*/
        List<Student> listStudent = studentController.getAll();
        List<String> studentIds = new ArrayList<>();
        studentIds = listStudent.stream().map(item -> item.getStudentname()).collect(Collectors.toList());
        jComboBox_New_StudentId.removeAllItems();
        studentIds.forEach((string) -> {
            jComboBox_New_StudentId.addItem(string);
        });
        if (jComboBox_New_StudentId.getSelectedItem() != null) {
            jDialogUser_New.pack();
            jDialogUser_New.setLocationRelativeTo(this);
            jDialogUser_New.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Phải thêm sinh viên trước khi thêm user", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        /*List<Student> listStudent = studentController.getAll();
        List<String> studentIds = new ArrayList<>();
        studentIds = listStudent.stream().map(item -> item.getId()).collect(Collectors.toList());
        jComboBox_Edit_StudentId.removeAllItems();
        studentIds.forEach((string) -> {
            jComboBox_Edit_StudentId.addItem(string);
        });
        if (jComboBox_Edit_StudentId.getSelectedItem() != null) {
            
            jDialogUser_Edit.pack();
            jDialogUser_Edit.setLocationRelativeTo(this);
            jDialogUser_Edit.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "báº¡n khÃ´ng thá»ƒ thÃªm user khi chÆ°a cÃ³ student nÃ o tá»“n táº¡i", "THÃ”NG BÃ�O", JOptionPane.ERROR_MESSAGE);
        }*/
        int count = tableUsers.getSelectedRow();
        if (count == -1) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn người dùng cần sửa", "THÔNG BÁO", HEIGHT);
        } else {
            List<Student> listStudent = studentController.getAll();
            List<String> studentIds = new ArrayList<>();
            studentIds = listStudent.stream().map(item -> item.getStudentname()).collect(Collectors.toList());
            jComboBox_Edit_StudentId.removeAllItems();
            studentIds.forEach((string) -> {
                jComboBox_Edit_StudentId.addItem(string);
            });
            jComboBox_Edit_StudentId.setSelectedItem(tableUsers.getValueAt(count, 3).toString());
            jDialogUser_Edit_txt_UserName.setText(tableUsers.getValueAt(count, 1).toString());
            jDIalogUser_Edit_txt_password.requestFocus();
            jDialogUser_Edit.pack();
            jDialogUser_Edit.setLocationRelativeTo(this);
            jDialogUser_Edit.setVisible(true);
        }
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void jDialogUser_New_btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogUser_New_btn_AddActionPerformed
        if (jDialogUser_New_txt_UserName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên đăng nhập", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            jDialogUser_New_txt_UserName.requestFocus();
        } else if (jDialogUser_New_txt_UserName.getText().trim().length() > 50) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không được vượt quá 50 kí tự", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDialogUser_New_txt_UserName.requestFocus();
            jDialogUser_New_txt_UserName.selectAll();
        } else if (userController.isExist(jDialogUser_New_txt_UserName.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập đã tồn tại", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDialogUser_New_txt_UserName.requestFocus();
            jDialogUser_New_txt_UserName.selectAll();
        } else if (jDIalogUser_New_txt_password.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mật khẩu", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            jDIalogUser_New_txt_password.requestFocus();
        } else if (jDIalogUser_New_txt_password.getPassword().length > 50) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được vượt quá 50 kí tự", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDIalogUser_New_txt_password.requestFocus();
            jDIalogUser_New_txt_password.selectAll();
        } else if (!Arrays.toString(jDIalogUser_New_txt_password1.getPassword())
                .equals(Arrays.toString(jDIalogUser_New_txt_password.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không chính xác", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDIalogUser_New_txt_password1.requestFocus();
            jDIalogUser_New_txt_password1.selectAll();
        } else {
            String studentId = (String) jComboBox_New_StudentId.getSelectedItem();
            String userName = jDialogUser_New_txt_UserName.getText();
            String passwork = Arrays.toString(jDIalogUser_New_txt_password1.getPassword());
            Users users = new Users(userName, passwork, studentId);
            int result = userController.addUser(users);
            if (result != 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            }
            btnUsers.doClick();
            jDialogUser_New_txt_UserName.setText("");
            jDialogUser_New_txt_UserName.requestFocus();
            jDIalogUser_New_txt_password.setText("");
            jDIalogUser_New_txt_password1.setText("");
            btnNewUser.doClick();
        }
    }//GEN-LAST:event_jDialogUser_New_btn_AddActionPerformed

    private void jDialogUser_New_btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDialogUser_New_btn_EditActionPerformed
        if (Arrays.toString(jDIalogUser_Edit_txt_password.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mật khẩu", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            jDIalogUser_Edit_txt_password.requestFocus();
        } else if (Arrays.toString(jDIalogUser_Edit_txt_password.getPassword()).length() > 50) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được vượt quá 50 kí tự", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDIalogUser_Edit_txt_password.requestFocus();
            jDIalogUser_Edit_txt_password.selectAll();
        } else if (!Arrays.toString(jDIalogUser_Edit_txt_password1.getPassword())
                .equals(Arrays.toString(jDIalogUser_Edit_txt_password1.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không chính xác", "THÔNG BÁO", JOptionPane.WARNING_MESSAGE);
            jDIalogUser_Edit_txt_password1.requestFocus();
            jDIalogUser_Edit_txt_password1.selectAll();
        } else {
            String studentId = (String) jComboBox_Edit_StudentId.getSelectedItem();
            String userName = jDialogUser_Edit_txt_UserName.getText();
            String passwork = Arrays.toString(jDIalogUser_Edit_txt_password1.getPassword());
            Users users = new Users(userName, passwork, studentId);
            int result = userController.editUser(users);
            if (result != 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            }
            btnUsers.doClick();
            jDialogUser_Edit.dispose();
        }
    }//GEN-LAST:event_jDialogUser_New_btn_EditActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        int[] countUsers = tableUsers.getSelectedRows();
        if (countUsers.length == 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn người dùng cần xóa", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean flag = false;
            for (int i = 0; i < countUsers.length; i++) {
                userController.delUser(tableUsers.getValueAt(countUsers[i], 1).toString());
                flag = true;
            }
            if (flag == true) {
                JOptionPane.showMessageDialog(null, "Xóa thành công", "THÔNG BÁO", HEIGHT);
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại", "THÔNG BÁO", ERROR);
            }
        }
        btnUsers.doClick();
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatch;
    private javax.swing.JButton btnDeleteBatch;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditBatch;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnEditUser;
    private javax.swing.ButtonGroup btnGroup_New_studentGender;
    private javax.swing.JButton btnNewBatch;
    private javax.swing.JButton btnNewStudent;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnUsers;
    private javax.swing.ButtonGroup buttonGroup_Edit_studentGender;
    private javax.swing.JComboBox<String> jComboBox_Edit_BatchIds;
    private javax.swing.JComboBox<String> jComboBox_Edit_StudentId;
    private javax.swing.JComboBox<String> jComboBox_New_BatchIds;
    private javax.swing.JComboBox<String> jComboBox_New_StudentId;
    private javax.swing.JPasswordField jDIalogUser_Edit_txt_password;
    private javax.swing.JPasswordField jDIalogUser_Edit_txt_password1;
    private javax.swing.JPasswordField jDIalogUser_New_txt_password;
    private javax.swing.JPasswordField jDIalogUser_New_txt_password1;
    private javax.swing.JDialog jDialogBatch_Edit;
    private javax.swing.JButton jDialogBatch_btnEdit;
    private javax.swing.JButton jDialogBatch_btn_add;
    private javax.swing.JLabel jDialogBatch_labelMessage1;
    private javax.swing.JLabel jDialogBatch_labelMessage2;
    private javax.swing.JDialog jDialogBatch_new;
    private javax.swing.JTextField jDialogBatch_txt_BatchId;
    private javax.swing.JTextField jDialogBatch_txt_editBatchId;
    private javax.swing.JDialog jDialogStudent_Edit;
    private javax.swing.JButton jDialogStudent_Edit_btn_add;
    private javax.swing.JTextField jDialogStudent_Edit_txt_StudentId;
    private javax.swing.JTextField jDialogStudent_Edit_txt_StudentName;
    private javax.swing.JDialog jDialogStudent_new;
    private javax.swing.JButton jDialogStudent_new_btn_add;
    private javax.swing.JTextField jDialogStudent_new_txt_StudentId;
    private javax.swing.JTextField jDialogStudent_new_txt_StudentName;
    private javax.swing.JDialog jDialogUser_Edit;
    private javax.swing.JTextField jDialogUser_Edit_txt_UserName;
    private javax.swing.JDialog jDialogUser_New;
    private javax.swing.JButton jDialogUser_New_btn_Add;
    private javax.swing.JButton jDialogUser_New_btn_Edit;
    private javax.swing.JTextField jDialogUser_New_txt_UserName;
    private javax.swing.JTextField jDialog_txt_BatchName;
    private javax.swing.JTextField jDialogbatch_txt_editBatchName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_Edit_Female;
    private javax.swing.JRadioButton jRadioButton_Edit_Male;
    private javax.swing.JRadioButton jRadioButton_Edit_Orther;
    private javax.swing.JRadioButton jRadioButton_New_Female;
    private javax.swing.JRadioButton jRadioButton_New_Male;
    private javax.swing.JRadioButton jRadioButton_New_Orther;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelBatch;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JPanel panelThongTin;
    private javax.swing.JPanel panelUsers;
    private javax.swing.JTable tableBatch;
    private javax.swing.JTable tableStudent;
    private javax.swing.JTable tableUsers;
    // End of variables declaration//GEN-END:variables
}
